#spring:
#  profiles:
#    include: classpath:config/liquibase-mysql.properties
#  datasource:
#    driver-class-name: ${jdbc.driverClass}
#    url: ${jdbc.url}
#    username: ${jdbc.username}
#    password: ${jdbc.password}
#  liquibase:
#    change-log: ${changeLogFile}
#    database-change-log-table: ${databaseChangeLogTableName}
#    database-change-log-lock-table: ${databaseChangeLogLockTableName}
spring:
  config:
    path: classpath:config/liquibase-mysql.properties